services:
  - type: web
    name: hire-papy
    runtime: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
